/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InternsIndexRouteImport } from './routes/interns.index'
import { Route as InternsInternIdRouteImport } from './routes/interns.$internId'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsIndexRoute = InternsIndexRouteImport.update({
  id: '/interns/',
  path: '/interns/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsInternIdRoute = InternsInternIdRouteImport.update({
  id: '/interns/$internId',
  path: '/interns/$internId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/follow-ups': typeof FollowUpsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/interns/': typeof InternsIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/follow-ups': typeof FollowUpsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/interns': typeof InternsIndexRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/follow-ups': typeof FollowUpsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/interns/': typeof InternsIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/follow-ups'
    | '/profile'
    | '/settings'
    | '/interns/$internId'
    | '/leads/$leadId'
    | '/interns/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/follow-ups'
    | '/profile'
    | '/settings'
    | '/interns/$internId'
    | '/leads/$leadId'
    | '/interns'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/follow-ups'
    | '/profile'
    | '/settings'
    | '/interns/$internId'
    | '/leads/$leadId'
    | '/interns/'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  FollowUpsRoute: typeof FollowUpsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  InternsInternIdRoute: typeof InternsInternIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  InternsIndexRoute: typeof InternsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns/': {
      id: '/interns/'
      path: '/interns'
      fullPath: '/interns/'
      preLoaderRoute: typeof InternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns/$internId': {
      id: '/interns/$internId'
      path: '/interns/$internId'
      fullPath: '/interns/$internId'
      preLoaderRoute: typeof InternsInternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  FollowUpsRoute: FollowUpsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  InternsInternIdRoute: InternsInternIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  InternsIndexRoute: InternsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
